# Generated by Django 5.0.1 on 2024-02-02 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_alter_news_published_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 2, 9, 23, 15, 673859, tzinfo=datetime.timezone.utc)),
        ),
    ]
