# Generated by Django 5.0.1 on 2024-02-03 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_alter_news_published_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 3, 6, 26, 34, 507916, tzinfo=datetime.timezone.utc)),
        ),
    ]
