# Generated by Django 5.0.1 on 2024-02-13 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0006_alter_news_image_alter_news_published_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 13, 19, 42, 20, 333469, tzinfo=datetime.timezone.utc)),
        ),
    ]
