# Generated by Django 5.0.2 on 2024-02-16 03:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0008_alter_news_published_time_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 16, 3, 57, 17, 327283, tzinfo=datetime.timezone.utc)),
        ),
    ]
